version: '3'

# start docker compose
# docker-compose up -d

# stop docker compose
# docker-compose stop

# stop and remove docker container
# docker-compose down

services:
  # Database
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
